services:

  sandbox-java17:
    build:
      context: ..
      args:
        - SANDBOX_USER_UID=999
        - SANDBOX_DIR=/sandbox
      dockerfile: ./docker/Dockerfile
    container_name: sandbox-java17
    image: sandbox-java17
    volumes:
      - ../src:/app/src
      - import:/sandbox/import:ro
    ports:
      - "9012:9012"
    networks:
      - localhost
    environment:
      - SANDBOX_USER_UID=999
      - SANDBOX_DIR=/sandbox
    pids_limit: 4096
    restart: on-failure
    command: gunicorn --pythonpath '/app/src' --bind 0:9012 app.main:app --reload -w 1

networks:
  localhost:
    external: true

volumes:
  import:
    external: true
